//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.05.27 at 04:19:50 PM MSK 
//


package com.github.vantonov1.maven.metadata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.vantonov1.maven.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Metadata_QNAME = new QName("http://maven.apache.org/METADATA/1.1.0", "metadata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.vantonov1.maven.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Versioning }
     * 
     */
    public Versioning createVersioning() {
        return new Versioning();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Plugin }
     * 
     */
    public Plugin createPlugin() {
        return new Plugin();
    }

    /**
     * Create an instance of {@link SnapshotVersion }
     * 
     */
    public SnapshotVersion createSnapshotVersion() {
        return new SnapshotVersion();
    }

    /**
     * Create an instance of {@link Snapshot }
     * 
     */
    public Snapshot createSnapshot() {
        return new Snapshot();
    }

    /**
     * Create an instance of {@link Versioning.Versions }
     * 
     */
    public Versioning.Versions createVersioningVersions() {
        return new Versioning.Versions();
    }

    /**
     * Create an instance of {@link Versioning.SnapshotVersions }
     * 
     */
    public Versioning.SnapshotVersions createVersioningSnapshotVersions() {
        return new Versioning.SnapshotVersions();
    }

    /**
     * Create an instance of {@link Metadata.Plugins }
     * 
     */
    public Metadata.Plugins createMetadataPlugins() {
        return new Metadata.Plugins();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Metadata }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Metadata }{@code >}
     */
    @XmlElementDecl(namespace = "http://maven.apache.org/METADATA/1.1.0", name = "metadata")
    public JAXBElement<Metadata> createMetadata(Metadata value) {
        return new JAXBElement<Metadata>(_Metadata_QNAME, Metadata.class, null, value);
    }

}
